# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ModelParameterInference <- function(Input, Freevec, Y, Missing, Y_uncertainty, Nl, Ne, Np, Nr, SampledPara, SampledVe, MeanOfPrior, VarOfPrior, Ve, Nve, Residualgroup, SdforParameters, SdforVe, Loglike, Burnin, Thi, Totalite, Order, Lowerlimit, Upperlimit, AccParameters, AccVe, Model, NeNl, Transformation, nRandom_para, nRandom_ve, uRandom_para, uRandom_ve) {
    .Call('_GenomeBasedModel_ModelParameterInference', PACKAGE = 'GenomeBasedModel', Input, Freevec, Y, Missing, Y_uncertainty, Nl, Ne, Np, Nr, SampledPara, SampledVe, MeanOfPrior, VarOfPrior, Ve, Nve, Residualgroup, SdforParameters, SdforVe, Loglike, Burnin, Thi, Totalite, Order, Lowerlimit, Upperlimit, AccParameters, AccVe, Model, NeNl, Transformation, nRandom_para, nRandom_ve, uRandom_para, uRandom_ve)
}

ModelParameterInference_PassMatrix <- function(Input, Freevec, Y, Missing, Y_uncertainty, Nl, Ne, Np, Nr, SampledPara, SampledVe, MeanOfPrior, VarOfPrior, Ve, Nve, Residualgroup, SdforParameters, SdforVe, Loglike, Burnin, Thi, Totalite, Order, Lowerlimit, Upperlimit, AccParameters, AccVe, Model, NeNl, Transformation, nRandom_para, nRandom_ve, uRandom_para, uRandom_ve) {
    .Call('_GenomeBasedModel_ModelParameterInference_PassMatrix', PACKAGE = 'GenomeBasedModel', Input, Freevec, Y, Missing, Y_uncertainty, Nl, Ne, Np, Nr, SampledPara, SampledVe, MeanOfPrior, VarOfPrior, Ve, Nve, Residualgroup, SdforParameters, SdforVe, Loglike, Burnin, Thi, Totalite, Order, Lowerlimit, Upperlimit, AccParameters, AccVe, Model, NeNl, Transformation, nRandom_para, nRandom_ve, uRandom_para, uRandom_ve)
}

